---
title: "PROJECT PROPOSAL"
subtitle: "POLI490 INDEPENDENT READING & RESEARCH"
author: "Maelee Ane Seres"
date: "9/16/2019"
output: pdf_document
---

# BACKGROUND

The purpose of this independent study is to continue and further develop an assignment given in POLI359:

**Adopt A Treaty Project**  

> *Your assignment is to tell a coherent story about the historical treaty you have chosen by providing an account of its objectives, design, and effect. The premise of the project falls under the Rational Design of Institutions, which claims that institutions are "rational, negotiated responses to the problems international actors face." As such, they should vary in systematic ways.*

In the original assignment, I focused on a single treaty (Defensive Alliance Between Great Britain and Russia), in which I argued that under the premise that institutions are rational in their design, the treaty’s reference to God and the Holy Trinity was a strategic choice to ensure both credibility and compliance. As support, I used the biblical standard for treaties, looking at the Gibeonite Treaty and the 5 Main Covenants of the Old Testament. 

# INITIAL GOALS & RESEARCH QUESTIONS

Working off of the original assignment, in this study I would like to:

* Read and analyze at more of the peace treaties from the database to see if a similar pattern emerges.

* Use the treaties as a unit of analysis to create a quantitative component to potentially model reference to Christian authority as a credibility signal. I am hoping to create a dataset based off the treaties, and then use the data to see if there is a link between credibility and Christianity.

    + Would use definitive/explicit Christian references meaning "There shall be a Christian peace", "Made in the name of God", "In the name of the Holy Trinity", etc. (of which are usually located in the opening or final sentence of the treaty).

* Potentially look into the effect this reference to Christian authority specifically had on state behaviour. In the original paper I focused more on the treaty as a result of state interest, looking at the objectives and design components. 

* Additionally from my paper, I found that the biblical treaties/covenants, were enforced through the later actions of God, creating a potential enforcement mechanism, and I think it would be interesting to see if that applies to the treaties from the database, made under the same conditions. 

* Potential questions: Before international institutions, are treaties that reference God more credible than without? Does this reference to Christian authority create an enforcement mechanism?
